name: speech_recognition
description: A flutter plugin to use the speech recognition on iOS and Android
version: 1.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"
  
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kavacode.flutter.speechrecognition
        pluginClass: SpeechRecognitionPlugin
      ios:
        pluginClass: SpeechRecognitionPlugin


